steps:
  - name: "gcr.io/cloud-builders/go"
    env: ["PROJECT_ROOT=secrets"]
    args: ["install", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/secrets:0.0.1", "."]

images: ["gcr.io/${PROJECT_ID}/secrets:0.0.1"]
